name: build-and-test

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: ./github/actions/setup-python
    - name: Run build
      shell: bash
      run: python -m build
    # TODO: move test dependencies to a separate file
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install -e .
        python -m pip install pytest mock
    - name: Run pytest
      shell: bash
      run: pytest
