name: pr

on: pull_request

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build and test
        uses: ./.github/actions/build-and-test
