name: pr

on: pull_request

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install dependencies
        # TODO: move test dependencies to a separate file
        run: |
          python -m pip install -e .
          python -m pip install pytest mock
      - name: Run pytest
        run: pytest
